name: Deploy Security Resources

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OC CLI
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz -o oc.tar.gz
          tar -xzf oc.tar.gz
          sudo mv oc /usr/local/bin/
          oc version

      - name: Login to OpenShift
        run: |
          oc login ${{ secrets.OCP_API }} --token=${{ secrets.OCP_TOKEN }} --insecure-skip-tls-verify

      - name: Apply security resources
        run: |
          oc project jessica-cuenca-dev
          oc apply -f ocsecurity.yaml
